# AutoGenerated by Basalt
$: << 'modules'

### module(.yml): std/_basalt.rb
require 'std/load'
### module(.yml): data_model/_basalt.rb
require 'data_model/load'
### module(.yml): render_primitives/_basalt.rb
require 'render_primitives/load'
### module(.yml): debug/_basalt.rb
require 'debug/load'
### module(.yml): quick/_basalt.rb
require 'quick/numeric'
### module(.yml): lunar/_basalt.rb
require 'lunar/load'
### module(.yml): scheduler/_basalt.rb
require 'scheduler/load'
